### ISSUE TITLE
Add a note to use lower parallelism during build on low RAM systems

### ISSUE THREAD

**Issue by pushfoo** [openc2e/openc2e#164]
This came up when I tried to run it in vagrant, but others might have issues with it as well. Chrooted chromebooks, raspis, and other hardware may come up against RAM limits.

**Comment by ligfx** [comment]
@pushfoo Thanks for reporting the issue, but I don't want to put this in the README since it's general C/C++ documentation and not specific to openc2e. A quick Google of the error message also returns many results saying "reduce the parallelism," so we don't really need special documentation for this one case.

**Comment by pushfoo** [comment]
@ligfx I think it's worth considering noting it somewhere, even if not in the main readme. Not everyone knows how to use C++ build systems. If we start offering binaries, this will be less of an issue

**Comment by ligfx** [comment]
@pushfoo Sorry, I disagree. It's a C++ project, there will always be more issues with C++ build systems that could be documented but this isn't the place. And this issue seems relatively niche right now.
